lib/components/FormDrop.d.ts, lib/components/FormDrop.js, lib/components/FormDropPicture.d.ts, lib/index.d.ts, lib/index.js, lib/utils/bytes.d.ts, lib/utils/bytes.js, src/components/FormDrop.tsx, src/index.ts, src/utils/bytes.ts
- Se cambia el componente FormDropPicture a FormDrop.
- Se recibe si se quiere que el FormDrop sea de imagen o video, teniendo
varias props definidas por default según el tipo. Las mismas se
permiten sobreescribir.
[Como administrador quiero agregar un video a mi curso](https://humand.atlassian.net/browse/SQDP-102)
=> [STORY] Accept videos on FormDropPicture 

lib/components/DocumentItem.js, lib/components/FormDrop.js, lib/utils/files.d.ts, lib/utils/files.js, src/components/DocumentItem.tsx, src/components/FormDrop.tsx, src/utils/files.ts
- Si en el componente FormDrop se tiene un archivo de tipo PDF, pero el mismo está como url sin la información del título, el mismo no se muestra.
[Admin | Como admin quiero editar un curso](https://humand.atlassian.net/browse/SQDP-410)
=> [FIX] No mostrar titulo en FormDrop si no existe

lib/components/IconsMenu.d.ts, lib/components/IconsMenu.js, src/components/IconsMenu.tsx
- Se agrega la prop `disabled` al componente IconsMenu junto con lógica para evitar que se abra el menu y estilos para distinguir el estado disabled.
https://humand.atlassian.net/browse/SQEG-131
=> [STORY] Agregar 'disabled' a IconsMenu

lib/components/DocumentItem.js, src/components/DocumentItem.tsx
Problema:
- Se estaba abriendo los pdfs primero haciendo un fetch a la url y de esta obteniendo el blob, que se usaba para abrirlo con un botón. Esto no funcionaba para Chrome.
- Se cambia el Button por un Link, con la url correspondiente al pdf que se quiere mostrar. El mismo se abre en una pestaña nueva o se descarga según la configuración de cada browser.
[Detalles de creación y edición de cursos](https://humand.atlassian.net/browse/SQDP-610)
=> [SQDP-610] Abrir pdf de FormDrop

lib/components/IconsMenu.d.ts, lib/components/IconsMenu.js, src/components/IconsMenu.tsx
- Se agrega la posibilidad de tener opciones disabled en vez de optar por todo el menu deshabilitado o no.
=> Add disabled prop to IconsMenu option

lib/components/DocumentItem.d.ts, lib/components/DocumentItem.js, lib/components/FormDrop.d.ts, lib/components/FormDrop.js, src/components/DocumentItem.tsx, src/components/FormDrop.tsx
- Se agrega el tipo 'FILE' al componente `FormDrop`, el cuál acepta cualquier tipo de archivo.
[Trainings - back & admin | Poder agregar una lección del tipo scorm](https://humand.atlassian.net/browse/SQDP-719)
=> [SQDP-719] Courses | Add file type to FormDrop

lib/components/NewModal.d.ts, src/components/NewModal.tsx
Se agrega (e?) => en el onClose para poder handlear un stopPropagation y evitar que al cerrar el dialog se clickee algo detras.
=> NewModal | Permitir un parametro en el onClose

lib/components/IconsMenu.d.ts, lib/components/IconsMenu.js, src/components/IconsMenu.tsx
Se busca lograr una nueva version del IconsMenu. Icono como avatar con fondo gris, con una arrow opcional como veremos en la imagen
`Sin arrow ni divider (default):`
`Con arrow y divider:`
=> IconsMenu | Actualizar componente a nuevo estilo (pre DS3)

lib/components/FormDrop.d.ts, lib/components/FormDrop.js, src/components/FormDrop.tsx
Como se detalla [aca](https://www.notion.so/humand-co/Attachments-2-0-5095a62075524668b34cfc72d9127110), pasaremos a usar el servicio de attachments que disponibiliza la api para crear archivos. En este PR se modifica el componente `FormDrop` para que permita esta nueva funcionalidad de manera optativa - mediante la prop `attachmentFormatEnabled`
=> Add Attachment Format Support

lib/theme/hugo/components.js, src/theme/hugo/components.ts
Se agregan los estilos de variantes y colores para el componente Badge.
Se agrega estilos `globalXXS` de tipography para evitar crear el componente wrapper. 
[SQPM-3596](https://humand.atlassian.net/browse/SQPM-3596)
[SQPM-3596]: https://humand.atlassian.net/browse/SQPM-3596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SQPM-3597] DS3 | Badge

lib/components/IconsMenu.d.ts, lib/components/IconsMenu.js, src/components/IconsMenu.tsx
Se suma la prop iconButtonProps al IconsMenu para poder pasarle `sx` u otras props importantes
=> Add iconButtonProps for IconsMenu

lib/components/HorizontalStepper.d.ts, lib/components/HorizontalStepper.js, src/components/HorizontalStepper.tsx
- Se agregan los siguientes componentes que se reciben por props para configurar `HorizontalStepper`:
- `titleLeftComponent`.
- `actions`.
[Trainings | Guardar como borrador](https://humand.atlassian.net/browse/SQDP-884)
=> [SQDP-884] Agregar componentes a HorizontalStepper

lib/utils/validations.js, src/utils/validations.ts
Devolver true si el input es null o undefined porque trajo errores. Aparentemente el sanitize cambia el undefined probablemente por null y al cambiar ese valor la validacion da error.
=> Tech | Fix sanitize 

lib/components/Title/Title.d.ts, lib/components/Title/Title.js, lib/components/Tooltip/Tooltip.d.ts, lib/components/Tooltip/Tooltip.js, src/components/Title/Title.stories.tsx, src/components/Title/Title.tsx, src/components/Tooltip/Tooltip.stories.tsx, src/components/Tooltip/Tooltip.tsx
Se suma el componente Tooltip. No se sumo la variante `isRemovable` ya que no esta claro que es lo que remueve (parece un comportamiento mas de mobile) y no es necesario ahora en Analitics
Se suma el componente de Tooltip
Se suma tooltip como posibilidad al Title
[Card](https://humand.atlassian.net/browse/SQXS-1485)
=> Added tooltip component

lib/components/Input/CustomInput.d.ts, lib/components/Input/CustomInput.js, lib/components/Input/CustomSelect.d.ts, lib/components/Input/CustomSelect.js, lib/components/Input/FormInputClassic.d.ts, lib/components/Input/InputClassic.d.ts, lib/components/Input/InputClassic.js, lib/components/Input/InputSelect.d.ts, src/components/Input/CustomInput.tsx, src/components/Input/CustomSelect.tsx, src/components/Input/FormInputClassic.tsx, src/components/Input/InputClassic.stories.tsx, src/components/Input/InputClassic.tsx, src/components/Input/InputSelect.tsx
Agrego opcion multiline al inputclassic.
Tambien muevo de lugar algunos types para que el input en sí no dependa de las props del wrapper que tiene label+input+helper
https://humand.atlassian.net/browse/SQJG-2906
=> Add multiline to InputClassic

lib/hooks/useServerPagination.d.ts, lib/hooks/useServerPagination.js, src/hooks/useServerPagination.tsx
Se agregan los parametros `defaultQuery`, `defaultLimit` y `defaultPage` al hook `useServerPagination` para poder configurar estos valores en caso de que no sean los defaults. Por ej., para guardar valores de paginacion en la URL y setterar los valores iniciales correctos.
=> Server pagination | Add default values

lib/components/Menu/Menu.d.ts, lib/huexports.d.ts, lib/huexports.js, src/components/Menu/Menu.tsx, src/huexports.ts
- Se hace el `footer` opcional en `Menu`.
- Se agregan los exports de HuGo para `List`, `ListItem` y `ListItemSkeleton`.
=> [SQDP-NO-CARD] DS | Fixes en menu y list

lib/components/Breadcrumbs/Breadcrumbs.js, lib/components/Breadcrumbs/types.d.ts, lib/components/Link/Link.d.ts, lib/components/Link/Link.js, src/components/Breadcrumbs/Breadcrumbs.tsx, src/components/Breadcrumbs/types.ts, src/components/Link/Link.tsx
- Se agrega la opción de tener los links de breadcrumbs con `onClick` en vez de `href`.
=> [NO-CARD] Breadcrumbs | Links with onClick

lib/components/ButtonGroup/ButtonGroup.d.ts, lib/components/ButtonGroup/ButtonGroup.js, lib/components/Snackbar/Snackbar.js, src/components/ButtonGroup/ButtonGroup.stories.tsx, src/components/ButtonGroup/ButtonGroup.tsx, src/components/Snackbar/Snackbar.tsx
Usando Snackbar & ButtonGroup en una nueva feature, se encontraron 2 cosas:
- ButtonGroup: Falta la posibilidad de hacerse click en la opcion seleccionada y que no quede ninguna
- Snackbar: Considerar caso en que se use **description** sin **title** y haya desalineaciones / desperdicio de espacios, y lo mismo para aprovechar todo el ancho si no hay `Cancel Action`
=> [-] Improvements Snackbar & ButtonGroup

lib/components/Switcher/Switcher.d.ts, lib/components/Switcher/Switcher.js, lib/components/Toggle/Toggle.d.ts, lib/components/Toggle/Toggle.js, lib/huexports.d.ts, lib/huexports.js, src/components/Switcher/Switcher.stories.tsx, src/components/Switcher/Switcher.tsx, src/components/Toggle/Toggle.tsx, src/huexports.ts
Note: dark mode will be put on hold. It should be automatic once a global dark mode pallette is implemented
[SQSH-1819](https://humand.atlassian.net/browse/SQSH-1819)
[SQSH-1819]: https://humand.atlassian.net/browse/SQSH-1819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SQSH-1819] Add switcher

lib/components/Title/Title.js, src/components/Title/Title.tsx
- Se centran los tooltips en el componente de title.
- Antes:
- Después:
=> [NO-CARD] Title | Ajustar alignment de tooltips

lib/hooks/useServerPagination.js, src/hooks/useServerPagination.tsx
the setOrder had as new value the operation `newOrder || order === 'DESC' ? 'ASC' : 'DESC'`, which was being taken implicitly as `(newOrder || order === 'DESC') ? 'ASC' : 'DESC'`
By putting explicit parenthesis we avoid this faulty logic
It now reads: `newOrder || (order === 'DESC' ? 'ASC' : 'DESC')`
Adding `order` to the dependency array was also necessary to keep the function up-to-date
NO CARD
=> Fix | Change operation precedence

lib/components/RadioButton/FormRadioButtonGroup.js, src/components/RadioButton/FormRadioButtonGroup.tsx
Problema: Al modificar el valor de algun radio group la prop `dirty` del form no se estaba seteando (siempre quedaba en false)
Solución: Agregarle la opción `shouldDirty` al setValue()
=> Form Radio Group - Fix dirty set

lib/components/ButtonGroup/ButtonGroup.js, src/components/ButtonGroup/ButtonGroup.tsx
Se logra que si esta fullWidth quede centrada la division y los botones de igual tamaño por pedido de Design
=> ButtonGroup | Fix alineacion

lib/components/Avatar/Avatar.d.ts, lib/components/Avatar/Avatar.js, lib/components/AvatarGroup/AvatarGroup.d.ts, lib/components/AvatarGroup/AvatarGroup.js, src/components/Avatar/Avatar.tsx, src/components/AvatarGroup/AvatarGroup.stories.tsx, src/components/AvatarGroup/AvatarGroup.tsx
- Se agrega prop opcional `totalAvatars` a **AvatarGroup**. La idea es que se pueda indicar el total de avatars sin tener que pasar el array con todos ellos. Por ejemplo el caso en que el tengamos 300 usuarios: solo necesitamos buscar la información de los primeros 4 usuarios (imagenes de perfil y nombre) y pasamos el count/length bajo `totalAvatars`.
- Se hace un ajuste en la destructuración de props de **Avatar** para que no se sobrescriba el sx.
Antes, al aplicarle `sx={{ ml: 10 }}` sobrescribe el resto de los estilos
Despues
=> Avatar Group | Agregado prop custom total

lib/components/Input/CustomHelperText.js, lib/components/Input/CustomInput.js, src/components/Input/CustomHelperText.tsx, src/components/Input/CustomInput.tsx
Al utilizar el input classic en web aparecía el siguiente error en consola
Esto sucede porque el componente `<FormHelperText />` utilizado en el Input Classic  es un tag `<p>`
Solución: Se agregó `component="span"` al Stack utilizado bajo `<FormHelperText />` para que el anidado deje de ser inválido.
---
Aparte:
- Se cambio el color del placeholder para el input en modo multiline (textarea), ya que no tenia el mismo color al input común.
Ninguna
=> Input Classic |  ajuste Stack de helperText

lib/components/ProgressBar/ProgressBar.d.ts, lib/components/ProgressBar/ProgressBar.js, src/components/ProgressBar/ProgressBar.stories.tsx, src/components/ProgressBar/ProgressBar.tsx
Default queda en 4 como estaba, pero se permite configurar ese height
=> ProgressBar | Set bar height

lib/components/Snackbar/Snackbar.js, lib/components/Title/Title.js, src/components/Snackbar/Snackbar.tsx, src/components/Title/Title.tsx
> **Title**
- No funcionaba bien las **ellipsis** con un titulo largo
> **Snackbar**
- Se setean los estilos de forma manual, ya que como el `SnackbarProvider` en nuestro proyecto esta por fuera del ThemeProvider, si le aplicamos estilos de Hugo no los toma. Con lo cual, temporalmente y mientras el `HugoProvider` no sea general para todo el proyecto, la mejor opcion es para **este** caso aplicar los estilos de typography manualmente.
=> Title | Ellipsis max lines

lib/components/AvatarGroup/AvatarGroup.js, lib/components/Skeleton/Skeleton.js, lib/components/Snackbar/Snackbar.d.ts, lib/components/Snackbar/Snackbar.js, lib/components/Tabs/Tabs.d.ts, lib/components/Tabs/Tabs.js, src/components/AvatarGroup/AvatarGroup.tsx, src/components/Skeleton/Skeleton.tsx, src/components/Snackbar/Snackbar.stories.tsx, src/components/Snackbar/Snackbar.tsx, src/components/Tabs/Tabs.stories.tsx, src/components/Tabs/Tabs.tsx
Se realizan cambios en los componentes para SQEG-910 (no están especificados en la card)
-  Se cambia el orden de props de SX del `Skeleton` para que el borderRadius pueda ser sobrescrito de ser necesario
- Se agrega una prop de `autoHideDuration` al snackbar para especificar el tiempo de cierre del `Snackbar`
- Se agrega prop `value` al componente `Tabs` para que se pueda pasar un controlledValue en caso de necesitarlo
- En `avatarGroup` diseño eligió simplificar el contador de avatars para que muestre directamente las unidades de mil (sin mostrar, por ejemplo: '1.5k' ) ya que ocupa mucho lugar y genera ciertas inconsistencias.
https://github.com/user-attachments/assets/c0a04330-3a0e-4734-9bfd-fb2755c54df6
Ninguna
=> [No card] - Ajustes varios en componentes

lib/components/Snackbar/Snackbar.js, src/components/Snackbar/Snackbar.tsx
Se agregan keys a los elementos de un array para evitar que se muestre el warning de:
_Warning: Each child in a list should have a unique "key" prop._
=> Remove Warning | Add key prop to array elements

lib/components/Input/CustomInput.js, src/components/Input/CustomInput.tsx, src/components/Input/InputClassic.stories.tsx
Le agrego un margin right por default al startAdornment para que no haya que ponerlo a mano. Doy por hecho que siempre va a ser un svg.
Intenté hacerlo con las clases de MUI pero no hay forma de que me tome las clases del adornment
=> [CustomInput] Add margin-right to startadornment

lib/components/Avatar/Avatar.js, src/components/Avatar/Avatar.tsx
- Agrego prioridades al Avatar: se renderiza el `src`, si no hay el `text` y si no hay el `Icon`
- Agrego un Icon default por si no se le pasa nada (`IconUser`)
=> Avatar | Add priorities to the Avatar

lib/components/Drawer/Drawer.d.ts, lib/components/Drawer/Drawer.js, src/components/Drawer/Drawer.stories.tsx, src/components/Drawer/Drawer.tsx
- Agrego una prop de `hasBackButton` al drawer para mostrar la flechita para atrás
- Al clickearla, se corre `onClose`. Si en el futuro necesitamos configurarlo podemos hacerlo, pero por lo que vi siempre es para cerrar el drawer
=> Drawer | Add hasBackButton prop

lib/theme/hugo/typography.js, src/theme/hugo/typography.ts
- Se aumenta el valor del `fontWeightSemiBold` de 500 a 600 para que sea consistente con los diseños en figma
No hay card
=> General | Modify theme semiBold fontWeight

lib/components/ProgressBar/ProgressBar.d.ts, lib/components/ProgressBar/ProgressBar.js, src/components/ProgressBar/ProgressBar.tsx
Se agrega precision decimal que por default sigue siendo como estaba (0) pero se puede configurar 1 o 2 decimales en lo que es el label del %.
=> [] ProgressBar | Add decimal precision

lib/components/Tabs/Tabs.js, src/components/Tabs/Tabs.tsx
Se soluciona un bug donde la tab seleccionada no se mostraba en azul y el ancho del divider era de 2px en vez de 1
=> [NO-CARD] fix: Tabs color and margin

lib/theme/hugo/components.js, src/theme/hugo/components.ts
Se agrega el estilo border-color al Divider para poder ver el color neutralDivider ya que, si bien el background color esta correcto, eso no es lo que se muestra en la web:
Actualmente el boder color es  `rgba(0, 0, 0, 0.12)`. Se deberia mostrar `#E9E9F4` segun el [diseño](https://www.figma.com/design/mLRasWttlTuAWuE0MeBeWD/Components?node-id=87-280&t=Hpyfc3mUhLJbGALC-0) 
Con border-color: rgba(0, 0, 0, 0.12)
Con el boder-color: #E9E9F4
https://humand.atlassian.net/browse/SQSH-1973
=> [SQSH-1973] Divider | Fix boder color 

lib/theme/hugo/components.js, src/theme/hugo/components.ts
Dejo la configuración "default" de material-ui para el divider, que coincide con nuestro figma. Lo que le da color al divider es su unico border.
Como el elemento en sí tiene altura/width 0, el `backgroundColor` no debería influir en nada. Igual lo mantengo por si en alguna pantalla quieren customizarlo para hacerlo más grueso.
Antes
Despues
=> [Divider] Fix divider

lib/hooks/useHuPagination.d.ts, lib/hooks/useHuPagination.js, src/hooks/useHuPagination.tsx
- Cuando el search tenía menos de 3 caracteres se setteaban los urlParams en vacío y eso hacía que el valor de search pase a ser vacío. Esto generaba que cuando el usuario tenía 3 caracteres y borraba una, se le borraba todo el input.
[Libraries | Ajustes QA Formulario ](https://humand.atlassian.net/browse/SQDP-1509)
=> Fix search with less than 3 characters

lib/components/Drawer/Drawer.js, lib/hooks/useSidesheet.d.ts, lib/hooks/useSidesheet.js, lib/index.d.ts, lib/index.js, src/components/Drawer/Drawer.stories.tsx, src/components/Drawer/Drawer.tsx, src/hooks/useSidesheet.tsx, src/index.ts
Hook implementado para necesidad especifica
- Analogo a `useDrawer`
- Con persistencia y export de style para que el container sea desplazado en la apertura del sidesheet
- Fix en Drawer para que no se muestre siempre la barra lateral del scroll:  ✅  |  ❌ 
[SQRC-129](https://humand.atlassian.net/browse/SQRC-129)
[SQRC-129]: https://humand.atlassian.net/browse/SQRC-129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SQRC-129] Sidesheet | useSidesheet based on Drawer

lib/components/List/ListItem.d.ts, lib/components/List/ListItem.js, lib/components/Menu/MenuList.d.ts, lib/components/Menu/MenuList.js, lib/components/posts/CreatePost.d.ts, lib/components/posts/CreatePost.js, lib/components/posts/Post.d.ts, lib/components/posts/Post.js, lib/components/posts/i18n.js, lib/huexports.d.ts, lib/huexports.js, lib/utils/array.d.ts, lib/utils/array.js, src/components/List/ListItem.tsx, src/components/Menu/MenuList.stories.tsx, src/components/Menu/MenuList.tsx, src/components/posts/CreatePost.stories.tsx, src/components/posts/CreatePost.tsx, src/components/posts/Post.stories.tsx, src/components/posts/Post.tsx, src/components/posts/i18n.ts, src/huexports.ts, src/utils/array.ts
- AgregoMenuList
- Agrego al ListItem la opción de cambiarle el `component`. Esto es porque cuando lo usamos dentro de un MenuList -> MenuItem, lo estamos usando como descendiente de otro li y tira un error en consola.
- Agrego al ListItem action la opcion de mandar le action completa, para poder usarlo con MenuList. No me encanta este modo porque me parece más correcto para el DS pasarle la configuración y que el componente se encargue de renderizarlo bien. Pero para usarlo con MenuList necesito pasarle el boton ya renderizado y creo que eventualmente va a ser el caso más comun.
- Modifico el CreatePost para soportar edición y fixear estilos
=> Edit post + MenuList
