HumandDev/material-hu

- lib/components/CustomStepper.d.ts
- lib/index.d.ts
- src/components/CustomStepper.tsx
- src/index.ts
> Export CustomStepperProps

- lib/components/SideStepper.d.ts
- lib/components/SideStepper.js
- lib/index.d.ts
- lib/index.js
- src/components/SideStepper.tsx
- src/index.ts
> Add SiteStepper

- lib/components/CustomStepper.js
- src/components/CustomStepper.tsx
Step checked cuando ya esta ubicado en uno siguiente
> CustomStepper | Add Checked Icon

- notistack/index.ts
> Export notistack

- lib/theme/base/create-components.js
- src/theme/base/create-components.tsx
Se agregan los colores de las 4 variantes de Alert en funcion al [Design System](https://www.figma.com/file/mQ3rxkr8MdoqkvVVNqjvHJ/Humand_DS_v.2.0?node-id=6646%3A50218&mode=dev)
> Mui Alert variants colours

- dropzone/index.ts
- lib/components/FormDropPicture.d.ts
- lib/components/FormDropPicture.js
- lib/components/HorizontalStepper.d.ts
- lib/components/HorizontalStepper.js
- lib/index.d.ts
- lib/index.js
- package-lock.json
- package.json
- src/components/FormDropPicture.tsx
- src/components/HorizontalStepper.tsx
- src/index.ts
- Se agregan los componentes:
- HorizontalStepper.
- FormDropPicture.
- Se exporta la librería react-dropzone como dropzone.
> [STORY] Agregar HorizontalStepper y FormDropPicture

- src/components/CustomStepper.tsx
Se le agrega la prop expanded al componente Step de Custom Stepper para poder lograr algo como lo siguiente:
> add expanded prop to Step component

- lib/components/FormRadioCustomGroup.d.ts
- lib/components/FormRadioCustomGroup.js
- lib/index.d.ts
- lib/index.js
- lib/theme/material-hu.d.ts
- src/components/FormRadioCustomGroup.tsx
- src/index.ts
- src/theme/material-hu.ts
- Se agrega un componente de RadioGroup customizado.
---
- [Configuración exitosa de los detalles del curso](https://humand.atlassian.net/browse/SQDP-56)
> [STORY] Agregar FormRadioCustomGroup

- lib/components/pagination/SearchBarController.d.ts
- lib/hooks/useClientPagination.d.ts
- lib/hooks/useClientPagination.js
- lib/hooks/useServerPagination.js
- lib/index.d.ts
- lib/index.js
- package-lock.json
- package.json
- src/components/pagination/SearchBarController.tsx
- src/hooks/useClientPagination.tsx
- src/hooks/useServerPagination.tsx
- src/index.ts
Se agrega hook `useClientPagination` para el backoffice. En el backoffice se renombra el hook: `useQueryingAndPagination`
https://humand.atlassian.net/browse/SQPM-2596
> Hooks | useClientPagination

- lib/components/pagination/SearchBarController.d.ts
- lib/components/pagination/SearchBarController.js
- lib/hooks/useServerPagination.d.ts
- lib/hooks/useServerPagination.js
- src/components/pagination/SearchBarController.tsx
- src/hooks/useServerPagination.tsx
Se agrega el parametro isPeopleExperience en useServerPagination que se agrego ahora en backoffice mientras estaba subiendo estos cambios de useServerPagination
> hooks | se agrega isPeopleExperience en useServerPagination

- lib/hooks/useDebounce.d.ts
- lib/hooks/useDebounce.js
- lib/hooks/useServerPagination.js
- lib/index.d.ts
- lib/index.js
- src/hooks/useDebounce.ts
- src/hooks/useServerPagination.tsx
- src/index.ts
Se modificó el array de dependencias de useDebounce y no se exporta como default.
https://humand.atlassian.net/browse/SQSH-476
> Hooks | actualizacion dependencias use debounce

- public/browser-support.js
se agregó script de js para mostrar mensaje de actualización de navegador para determinadas versiones siguiendo referencia de caiuse.com
[SQPM-2755](https://humand.atlassian.net/browse/SQPM-2755)
[SQPM-2755]: https://humand.atlassian.net/browse/SQPM-2755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> General | Support PDFs Library on Old Browsers

- lib/components/pagination/SearchBarController.d.ts
- lib/components/pagination/SearchBarController.js
- lib/hooks/useClientPagination.d.ts
- lib/hooks/useClientPagination.js
- lib/hooks/useServerPagination.d.ts
- lib/hooks/useServerPagination.js
- src/components/pagination/SearchBarController.tsx
- src/hooks/useClientPagination.tsx
- src/hooks/useServerPagination.tsx
- Updated the API of `SearchController` to export a component instead. 
N/A
https://humand.atlassian.net/browse/SQOW-172
> [SQOW-172] Tech debt |  Update Searchbar API

- lib/components/pagination/SearchBarController.js
- lib/hooks/useServerPagination.js
- src/components/pagination/SearchBarController.tsx
- src/hooks/useServerPagination.tsx
Memoized the searchbar to avoid re-create the component when another value in the return of of the hook change.
https://github.com/HumandDev/material-hu/assets/151677573/b8db88e6-db50-41c8-8310-dddbe09bfc73
https://humand.atlassian.net/browse/SQOW-172
> [SQOW-172] Fix SearchbarController

- lib/hooks/useClientPagination.js
- src/hooks/useClientPagination.tsx
- Added missed memo in `useClientPagination`,
--
https://humand.atlassian.net/browse/SQOW-172
> [SQOW-172] Memoize searchbar for client pagination

- lib/components/DocumentItem.d.ts
- lib/components/DocumentItem.js
- lib/components/FormDrop.d.ts
- lib/components/FormDrop.js
- lib/index.d.ts
- lib/index.js
- src/components/DocumentItem.tsx
- src/components/FormDrop.tsx
- src/index.ts
- Se permite el formato pdf en FormDrop.
! Depende de #31 
[Admin | Como administrador quiero agregar una lectura al curso](https://humand.atlassian.net/browse/SQDP-103)
> [STORY] Accept pdfs on FormDrop

- lib/components/FormRadioCustomGroup.d.ts
- lib/components/FormRadioCustomGroup.js
- src/components/FormRadioCustomGroup.tsx
- Se agrega la prop 'rules' para poder pasarle validaciones a FormRadioCustomGroup
Ninguna
https://humand.atlassian.net/browse/SQEG-299
> [SQEG-299] Sites | Agregar 'rules' a FormRadioCustomGroup

- lib/components/CroppingModal.d.ts
- lib/components/CroppingModal.js
- lib/components/FormDrop.d.ts
- lib/components/FormDrop.js
- lib/index.d.ts
- lib/index.js
- package-lock.json
- package.json
- src/components/CroppingModal.tsx
- src/components/FormDrop.tsx
- src/index.ts
- Se agrega el componente `CroppingModal`.
- Se agrrega la opción `withCrop` al componente `FormDrop`.
! Este PR es necesario para https://github.com/HumandDev/humand-backoffice/pull/1662
[Ver cómo queda la imagen de portada](https://humand.atlassian.net/browse/SQDP-424)
> [SQDP-424] Trainings | Agregar CroppingModal

- lib/components/FormRichEditor.d.ts
- lib/components/FormRichEditor.js
- src/components/FormRichEditor.tsx
:warning: Este PR bloquea https://github.com/HumandDev/humand-backoffice/pull/1715
- Adds the following props to `FormRichEditor` component:
- `onEditorChange`.
- `onInit`.
[Trainings | Cambiar el limite de los caracteres permitidos](https://humand.atlassian.net/browse/SQDP-859)
> [SQDP-860] Add some editor props to FormRichEditor

- lib/components/peopleExperience/ActionsMenu.d.ts
- lib/components/peopleExperience/ActionsMenu.js
- lib/index.d.ts
- src/components/peopleExperience/ActionsMenu.tsx
The `onClick` error isn't been intercepted properly. So the `onClick` wrapped logic is not executed as expected.
--
https://humand.atlassian.net/browse/SQOW-570
> [SQOW-570] PX | Fix menu closing on select

- lib/index.d.ts
- lib/index.js
- src/components/peopleExperience/ListWithDivider.tsx
- src/index.ts
These componentes were missing exported, now solved that.
--
https://humand.atlassian.net/browse/SQOW-573
> [SQOW-574] PX | Export TabPanel and TabPanelItem

- lib/components/peopleExperience/SideTabNavigation.d.ts
- lib/components/peopleExperience/SideTabNavigation.js
- lib/index.d.ts
- src/components/peopleExperience/SideTabNavigation.tsx
As we have a new requirement, we are adding this layout option to allow wrap all tabs with the same component.
--
https://humand.atlassian.net/browse/SQOW-522
> [SQOW-522] PX | Add layout prop to side tab navigation

- lib/components/FormRichEditor.js
- src/components/FormRichEditor.tsx
Elimino la license `gpl` porque la version de tiny que estamos usando no la necesita.
https://humand.atlassian.net/browse/SQJG-2791
> TinyMCE - Remove GPL license

- lib/components/peopleExperience/SideTabNavigation.d.ts
- lib/components/peopleExperience/SideTabNavigation.js
- lib/index.d.ts
- src/components/peopleExperience/SideTabNavigation.tsx
--
--
https://humand.atlassian.net/browse/SQOW-629
> [SQOW-629] PX | Add styles option to SideTabNavigation

- lib/components/peopleExperience/SideTabNavigation.d.ts
- lib/components/peopleExperience/SideTabNavigation.js
- lib/index.d.ts
- src/components/peopleExperience/SideTabNavigation.tsx
> [SQOW-629] PX |  Corrections in tabs styling

- lib/components/FormRichEditor.d.ts
- lib/components/FormRichEditor.js
- src/components/FormRichEditor.tsx
Fix de estilos que no se estaban importando correctamente
https://humand.atlassian.net/browse/CSBM-1473
> Fix tinymce

- lib/components/peopleExperience/LinearProgressWithLabel.js
- src/components/peopleExperience/LinearProgressWithLabel.tsx
This component is only used in PX for now.
--
https://humand.atlassian.net/browse/SQOW-217
> [SQOW-217] PX | Update text styles for LinearProgress

- lib/components/Avatar.d.ts
- lib/components/Avatar.js
- src/components/Avatar.tsx
Se agrega el componente Avatar del DS3 con las siguientes condiciones:
- Si el size es small y tiene badge, se usará la variante "dot" del badge (por mas que se mande un badgeContent).
- Para diseño no se tendrán en cuenta los iconos dentro del badge, aunque por código se puede enviar igual.
Por defecto el color del Avatar es default.
[SQPM-3646](https://humand.atlassian.net/browse/SQPM-3646)
[SQPM-3646]: https://humand.atlassian.net/browse/SQPM-3646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SQPM-3646] DS3 | Avatar

- lib/components/FormRichEditor.js
- src/components/FormRichEditor.tsx
Fix de tiny para Safari y Firefox
https://humand.atlassian.net/browse/SQJG-2823
> Fix tiny in safari

- lib/utils/validations.js
- src/utils/validations.ts
Hago que devuelva true en caso de que el input no sea un string para casos como input de numeros
> Tech | Fix sanitize

- lib/components/peopleExperience/ValueIndicator.d.ts
- lib/components/peopleExperience/ValueIndicator.js
- lib/index.d.ts
- src/components/peopleExperience/ValueIndicator.tsx
Updates styles and add the option to customize the description tooltip.
--
https://humand.atlassian.net/browse/SQOW-432
> [SQOW-432] PX | Update `ValueIndicator`

- lib/components/Avatar/Avatar.d.ts
- lib/components/Avatar/Avatar.js
- src/components/Avatar/Avatar.stories.tsx
- src/components/Avatar/Avatar.tsx
Agrego icon al avatar
https://humand.atlassian.net/browse/SQJG-2906
> Add icons to avatar

- lib/components/SelectionCard/FormSelectionCard.d.ts
- lib/components/SelectionCard/FormSelectionCard.js
- lib/components/SelectionCard/SelectionCard.d.ts
- lib/components/SelectionCard/SelectionCard.js
- lib/huexports.d.ts
- lib/huexports.js
- src/components/SelectionCard/FormSelectionCard.tsx
- src/components/SelectionCard/SelectionCard.stories.tsx
- src/components/SelectionCard/SelectionCard.tsx
- src/huexports.ts
Se agrega componente SelectionCard dentro del mismo se podra agregar cualquier children
[](https://humand.atlassian.net/browse/)
> Add SelectionCard

- lib/theme/hugo/typography.js
- src/theme/hugo/typography.ts
Se setea el color default para textos definido en el design system `neutralText - #3A3A45`
> [No card] Set default color for typography

- .storybook/preview.tsx
- lib/components/Uploader/i18n.d.ts
- lib/components/Uploader/i18n.js
- lib/utils/i18n.d.ts
- lib/utils/i18n.js
- src/components/Uploader/i18n.ts
- src/utils/i18n.ts
- Agrego configuración de i18n para poder usarla con el idioma del proyecto admin/web 🎉 
- Agrego un ejemplo de archivo i18n para copiar
https://humand.atlassian.net/browse/SQJG-3052
> Add i18n config

- lib/components/ButtonGroup/ButtonGroup.d.ts
- lib/components/ButtonGroup/ButtonGroup.js
- src/components/ButtonGroup/ButtonGroup.stories.tsx
- src/components/ButtonGroup/ButtonGroup.tsx
ButtonGroup
[SQXS-1506](https://humand.atlassian.net/browse/SQXS-1506)
[SQXS-1506]: https://humand.atlassian.net/browse/SQXS-1506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ButtonGroup

- lib/components/Avatar/Avatar.d.ts
- lib/components/Avatar/Avatar.js
- lib/components/AvatarGroup/AvatarGroup.d.ts
- lib/components/List/List.d.ts
- lib/components/List/List.js
- lib/components/List/ListItem.d.ts
- lib/components/List/ListItem.js
- lib/components/List/ListItemSkeleton.d.ts
- lib/components/List/ListItemSkeleton.js
- lib/components/Title/Title.d.ts
- lib/components/Title/Title.js
- src/components/Avatar/Avatar.tsx
- src/components/AvatarGroup/AvatarGroup.tsx
- src/components/List/List.stories.tsx
- src/components/List/List.tsx
- src/components/List/ListItem.tsx
- src/components/List/ListItemSkeleton.tsx
- src/components/Title/Title.tsx
- Se agregan los componentes `List` y `ListItem`.
[DS | List](https://humand.atlassian.net/browse/SQDP-1199)
> [SQDP-1199] DS | List

- lib/components/Input/CustomDatePicker.d.ts
- lib/components/Input/CustomDatePicker.js
- lib/components/Input/DatePicker.d.ts
- lib/components/Input/DatePicker.js
- lib/components/Input/FormDatePicker.d.ts
- lib/components/Input/FormDatePicker.js
- src/components/Input/CustomDatePicker.tsx
- src/components/Input/DatePicker.stories.tsx
- src/components/Input/DatePicker.tsx
- src/components/Input/FormDatePicker.tsx
Se agrega el componente `DatePicker`
[Card](https://humand.atlassian.net/browse/SQCY-370)
> [SQCY-377] DS | Date picker

- lib/huexports.d.ts
- lib/huexports.js
- src/huexports.ts
Se suma el export de `HuTooltip` que faltaba
> Add Export tooltip

- lib/components/Accordion/Accordion.d.ts
- lib/components/Accordion/Accordion.js
- lib/huexports.d.ts
- lib/huexports.js
- src/components/Accordion/Accordion.stories.tsx
- src/components/Accordion/Accordion.tsx
- src/huexports.ts
Se agrega componente Accordion, el componente puede adoptar las dos formas que están en el figma.
- https://humand.atlassian.net/browse/SQRN-242
> Se agrega Accordion

- lib/components/Toggle/Toggle.d.ts
- lib/components/Toggle/Toggle.js
- src/components/Toggle/Toggle.stories.tsx
- src/components/Toggle/Toggle.tsx
Toggle base, sin Switch, queda preparado para usarse
[SQPM-3893](https://humand.atlassian.net/browse/SQPM-3893)
[SQPM-3893]: https://humand.atlassian.net/browse/SQPM-3893?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SQPM-3893] DS | Toggle

- lib/components/Dialog/Dialog.d.ts
- lib/components/Dialog/Dialog.js
- lib/huexports.d.ts
- lib/huexports.js
- src/components/Dialog/Dialog.stories.tsx
- src/components/Dialog/Dialog.tsx
- src/hooks/useModal.tsx
- src/huexports.ts
[Card](https://humand.atlassian.net/browse/SQPD-1493)
> DS3 | Dialog (Modal)

- lib/components/Link/Link.d.ts
- lib/components/Link/Link.js
- lib/huexports.d.ts
- lib/huexports.js
- src/components/Link/Link.stories.tsx
- src/components/Link/Link.tsx
- src/huexports.ts
Se agrega el componente Link
[Card](https://humand.atlassian.net/browse/SQPD-1488)
> DS3 | Link

- lib/components/Dialog/Dialog.d.ts
- lib/components/Dialog/Dialog.js
- src/components/Dialog/Dialog.stories.tsx
- src/components/Dialog/Dialog.tsx
- Se para a usar el LoadingButton en el Dialog.
> [NO-CARD] Dialog | Permitir loading en buttons

- lib/index.d.ts
- lib/index.js
- src/index.ts
Se agrega export faltante para `useDrawer`
> add missing useDrawer export

- lib/components/Dialog/Dialog.js
- lib/hooks/useModal.js
- src/components/Dialog/Dialog.tsx
- src/hooks/useModal.tsx
Cambios al dialog pedidos por diseño
> Dialog | Small ui adjustments

- lib/components/RadioButton/FormRadioButtonGroup.d.ts
- lib/components/RadioButton/FormRadioButtonGroup.js
- lib/huexports.d.ts
- lib/huexports.js
- src/components/RadioButton/FormRadioButtonGroup.tsx
- src/components/RadioButton/RadioButton.stories.tsx
- src/huexports.ts
- Se agrega el componente FormRadioButtonGroup
Ninguna
> [No card] Agregar Form Radio Button Group

- lib/components/Input/CustomSelect.d.ts
- lib/components/Input/CustomSelect.js
- lib/components/Input/FormInputSelect.d.ts
- lib/components/Input/InputSelect.d.ts
- lib/components/Input/InputSelect.js
- lib/components/Input/i18n.d.ts
- lib/components/Input/i18n.js
- lib/components/ProgressBar/ProgressBar.js
- lib/theme/hugo/components.js
- src/components/Input/CustomSelect.tsx
- src/components/Input/FormInputSelect.tsx
- src/components/Input/InputSelect.stories.tsx
- src/components/Input/InputSelect.tsx
- src/components/Input/i18n.ts
- src/components/ProgressBar/ProgressBar.tsx
- src/theme/hugo/components.ts
Fix de estilos de botones y progressbar
antes
despues
------
antes
despues
-------
Agrego opcion para deseleccionar
> Misc | Fix styles

- lib/components/RadioButton/RadioButton.d.ts
- lib/components/RadioButton/RadioButton.js
- src/components/RadioButton/RadioButton.tsx
Hago el onClick opcional, más que nada para los casos en que se usa dentro de un SelectionCard y no lo necesita
> [RadioButton] Make onclick optional

- lib/components/Input/CustomHelperText.js
- src/components/Input/CustomHelperText.tsx
Cambio el color del helper para que tome todos los subcomponentes. Habia estilos de mui que los estaban pisando así que le tuve que poner important :/ 
antes
despues
> Input - Fix helper color

- lib/components/CardContainer.d.ts
- lib/components/CardContainer.js
- lib/theme/hugo/components.js
- src/components/CardContainer.tsx
- src/theme/hugo/components.ts
- Agrego la opcion de onClick en el CardContainer, que agrega un CardActionArea
- Fixeo el color del divider
> CardContainer | Add CardAction

- lib/theme/hugo/components.js
- src/theme/hugo/components.ts
Fix de texttransform para que no quede uppercase
> [Button] Fix text transform

- src/components/Alert/Alert.stories.tsx
- src/components/ProgressBar/ProgressBar.stories.tsx
2 componentes que no tenian stories se aprovecha para sumarlas
> Alert + ProgressBar | Add stories

- lib/components/ButtonGroup/ButtonGroup.js
- src/components/ButtonGroup/ButtonGroup.tsx
Mini arreglo tras cambio en libreria, ahora el color none ya no funcionaba
> ButtonGroup fix

- lib/components/CardContainer/CardContainer.d.ts
- lib/components/CardContainer/CardContainer.js
- lib/components/Input/CustomHelperText.js
- lib/components/Input/CustomLabel.js
- lib/components/Input/DatePicker.d.ts
- lib/components/Input/DatePicker.js
- lib/components/Input/InputClassic.js
- src/components/CardContainer/CardContainer.tsx
- src/components/Input/CustomHelperText.tsx
- src/components/Input/CustomLabel.tsx
- src/components/Input/DatePicker.tsx
- src/components/Input/InputClassic.tsx
Hago que el label y helper disabled sea gris
Agrego opcion para el padding del CardContainer que puede tener 2 valores: 16 o 24
> fix input and card

- lib/components/Input/CustomInput.js
- src/components/Input/CustomInput.tsx
Se aplica un ajuste para que se vean bien los adornments
[](https://humand.atlassian.net/browse/)
> Ajuste de estilos en inputClassic

- lib/components/Drawer/Drawer.d.ts
- lib/components/Drawer/Drawer.js
- src/components/Drawer/Drawer.tsx
Cambio las props del button para que admita `loading`
> useDrawer | Change button props

- lib/components/Input/CustomInput.js
- src/components/Input/CustomInput.tsx
- src/components/Input/InputClassic.stories.tsx
> Input | Add input white background

- lib/components/Input/CustomInput.d.ts
- lib/components/Input/CustomInput.js
- lib/components/Input/FormInputClassic.d.ts
- lib/components/Input/InputClassic.d.ts
- lib/components/Input/InputClassic.js
- lib/components/posts/CreatePost.d.ts
- lib/components/posts/CreatePost.js
- src/components/Input/CustomInput.tsx
- src/components/Input/FormInputClassic.tsx
- src/components/Input/InputClassic.tsx
- src/components/posts/CreatePost.tsx
- Se adapta el `CreatePost`
- Se agrega la prop `minRows` al Input Classic, para los casos en que queremos inputs multiline pero que arranquen mostrando una sola row
https://humand.atlassian.net/browse/SQJG-3317
> Create posts 2

- lib/hooks/useHuPagination.d.ts
- src/hooks/useHuPagination.tsx
- Se fixean las props de los controllers de Search y Pagination, para useHuPagination.
> Fix useHuPagination controller props

- lib/components/ButtonGroup/ButtonGroup.js
- src/components/ButtonGroup/ButtonGroup.tsx
Se cambio el fontSize de 16 a 14px
> Fix button groups font

- lib/components/ButtonGroup/ButtonGroup.d.ts
- lib/components/ButtonGroup/ButtonGroup.js
- src/components/ButtonGroup/ButtonGroup.stories.tsx
- src/components/ButtonGroup/ButtonGroup.tsx
- Make optional check icon in button group component
https://github.com/user-attachments/assets/20d2b0a7-db7e-4013-85f3-faf2a22183b2
[SQPM-4109](https://humand.atlassian.net/browse/SQPM-4109)
[SQPM-4109]: https://humand.atlassian.net/browse/SQPM-4109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SQPM-4109] ButtonGroup | make optional check icon button group component

- lib/components/posts/Post.js
- src/components/posts/Post.tsx
> Fix post type

- lib/components/Input/FormInputClassic.d.ts
- src/components/Input/FormInputClassic.tsx
Se aplica este ajuste para que no se lance el error de linter.
> add disabled
